# Generated by Django 5.2.4 on 2025-09-19 01:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_savedsearch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='comparison',
        #     name='regions',
        # ),
        migrations.RemoveField(
            model_name='comparison',
            name='user',
        ),
        # migrations.RemoveField(
        #     model_name='news',
        #     name='region',
        # ),
        # migrations.RemoveField(
        #     model_name='review',
        #     name='region',
        # ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='savedsearch',
            name='unique_user_search_name',
        ),
        migrations.AlterUniqueTogether(
            name='savedsearch',
            unique_together={('user', 'name')},
        ),
        migrations.DeleteModel(
            name='Comparison',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        # migrations.DeleteModel(
        #     name='Region',
        # ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
