# Generated by Django 5.2.4 on 2025-10-17 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_comparison_regions_remove_comparison_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
    ]
