# Generated by Django 5.2.6 on 2025-10-06 06:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_importance', models.IntegerField(default=2, help_text='교육 중요도 (1-3)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('medical_importance', models.IntegerField(default=2, help_text='의료 중요도 (1-3)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('cost_importance', models.IntegerField(default=2, help_text='비용 중요도 (1-3)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('preferred_cost_level', models.CharField(choices=[('하', '하'), ('중', '중'), ('상', '상')], default='보통', max_length=20)),
                ('monthly_rent_budget', models.IntegerField(blank=True, help_text='월세 예산 (만원 단위)', null=True)),
                ('deposit_budget', models.IntegerField(blank=True, help_text='보증금 예산 (만원 단위)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(help_text='나이', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성'), ('O', '기타')], help_text='성별', max_length=1)),
                ('job', models.CharField(choices=[('student', '학생'), ('office_worker', '직장인'), ('freelancer', '프리랜서'), ('business_owner', '사업자'), ('public_servant', '공무원'), ('teacher', '교사'), ('healthcare', '의료진'), ('engineer', '엔지니어'), ('designer', '디자이너'), ('other', '기타')], help_text='직무', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
