# Generated by Django 5.2.4 on 2025-09-18 15:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="deposit_budget",
            field=models.IntegerField(
                blank=True, help_text="보증금 예산 (만원 단위)", null=True
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="medical_importance",
            field=models.IntegerField(
                default=3,
                help_text="의료 중요도 (1-5)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="monthly_rent_budget",
            field=models.IntegerField(
                blank=True, help_text="월세 예산 (만원 단위)", null=True
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        help_text="나이",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "남성"), ("F", "여성"), ("O", "기타")],
                        help_text="성별",
                        max_length=1,
                    ),
                ),
                (
                    "job",
                    models.CharField(
                        choices=[
                            ("student", "학생"),
                            ("office_worker", "직장인"),
                            ("freelancer", "프리랜서"),
                            ("business_owner", "사업자"),
                            ("public_servant", "공무원"),
                            ("teacher", "교사"),
                            ("healthcare", "의료진"),
                            ("engineer", "엔지니어"),
                            ("designer", "디자이너"),
                            ("other", "기타"),
                        ],
                        help_text="직무",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
