# Generated by Django 5.2.4 on 2025-10-16 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("regions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="정책 제목", max_length=200)),
                ("content", models.TextField(help_text="정책 내용")),
                ("summary", models.TextField(help_text="정책 요약", max_length=500)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("youth", "청년"),
                            ("housing", "주거"),
                            ("education", "교육"),
                            ("medical", "의료"),
                            ("transportation", "교통"),
                            ("business", "창업"),
                            ("employment", "취업"),
                            ("family", "가족"),
                            ("elderly", "노인"),
                            ("disability", "장애인"),
                            ("environment", "환경"),
                            ("culture", "문화"),
                            ("tourism", "관광"),
                            ("agriculture", "농업"),
                            ("fishery", "수산업"),
                            ("general", "일반"),
                        ],
                        default="general",
                        help_text="정책 카테고리",
                        max_length=20,
                    ),
                ),
                (
                    "target_age_min",
                    models.IntegerField(
                        blank=True, help_text="대상 연령 최소", null=True
                    ),
                ),
                (
                    "target_age_max",
                    models.IntegerField(
                        blank=True, help_text="대상 연령 최대", null=True
                    ),
                ),
                (
                    "target_income_min",
                    models.IntegerField(
                        blank=True, help_text="대상 소득 최소", null=True
                    ),
                ),
                (
                    "target_income_max",
                    models.IntegerField(
                        blank=True, help_text="대상 소득 최대", null=True
                    ),
                ),
                (
                    "support_amount",
                    models.IntegerField(blank=True, help_text="지원 금액", null=True),
                ),
                (
                    "support_period",
                    models.CharField(blank=True, help_text="지원 기간", max_length=100),
                ),
                (
                    "support_type",
                    models.CharField(blank=True, help_text="지원 유형", max_length=100),
                ),
                (
                    "application_start",
                    models.DateTimeField(
                        blank=True, help_text="신청 시작일", null=True
                    ),
                ),
                (
                    "application_end",
                    models.DateTimeField(
                        blank=True, help_text="신청 마감일", null=True
                    ),
                ),
                ("application_url", models.URLField(blank=True, help_text="신청 URL")),
                (
                    "contact_info",
                    models.CharField(blank=True, help_text="문의처", max_length=200),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="활성화 여부"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, help_text="추천 정책 여부"),
                ),
                ("priority", models.IntegerField(default=0, help_text="우선순위")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="등록자",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        help_text="해당 지역 (전국 정책의 경우 None)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="regions.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "정책",
                "verbose_name_plural": "정책들",
                "ordering": ["-priority", "-created_at"],
            },
        ),
    ]
