# Generated by Django 5.2.4 on 2025-10-17 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("regions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="비교 이름", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("traffic", "교통"),
                            ("education", "교육"),
                            ("medical", "의료"),
                            ("cost", "비용"),
                            ("environment", "환경"),
                            ("culture", "문화"),
                            ("safety", "안전"),
                            ("convenience", "편의시설"),
                        ],
                        default="general",
                        help_text="비교 카테고리",
                        max_length=20,
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(default=False, help_text="찜 목록 여부"),
                ),
                ("regions", models.ManyToManyField(to="regions.region")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
