# Generated by Django 5.2.6 on 2025-10-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='지역명')),
                ('medical_accessibility', models.FloatField(verbose_name='의료 평균접근성')),
                ('student_count', models.IntegerField(verbose_name='학생수')),
                ('teacher_count', models.IntegerField(verbose_name='교원수')),
                ('students_per_teacher', models.FloatField(verbose_name='교원 1인당 학생수')),
                ('deposit_manwon', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='보증금(만원)')),
                ('monthly_rent_manwon', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='월세금(만원)')),
                ('total_monthly_burden', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='종합월부담')),
                ('total_burden_grade', models.CharField(max_length=5, verbose_name='종합부담등급')),
                ('medical_grade', models.CharField(max_length=5, verbose_name='의료 등급')),
                ('education_infra_grade', models.CharField(max_length=5, verbose_name='교육 인프라 등급')),
                ('monthly_rent_grade', models.CharField(max_length=5, verbose_name='월세등급')),
                ('summary', models.TextField(verbose_name='summary')),
                ('latitude', models.FloatField(default=0.0, verbose_name='위도')),
                ('longitude', models.FloatField(default=0.0, verbose_name='경도')),
                ('population', models.IntegerField(default=0, verbose_name='인구수')),
                ('medical_score', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='의료 점수')),
                ('education_score', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='교육 점수')),
                ('cost_score', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='생활비 점수')),
            ],
            options={
                'verbose_name': '지역 정보',
                'verbose_name_plural': '지역 정보 목록',
            },
        ),
    ]
