# Generated by Django 5.2.4 on 2025-09-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='city',
            field=models.CharField(default='충청북도', help_text='소속 시/도', max_length=50),
        ),
    ]
