# Generated by Django 5.2.4 on 2025-09-03 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_region_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='medical_score',
            field=models.IntegerField(default=70, help_text='의료시설 점수', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
