# Generated by Django 5.2.4 on 2025-09-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_region_medical_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='latitude',
            field=models.FloatField(default=36.5, help_text='위도'),
        ),
        migrations.AddField(
            model_name='region',
            name='longitude',
            field=models.FloatField(default=127.5, help_text='경도'),
        ),
    ]
