# Generated by Django 5.2.4 on 2025-09-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0004_region_latitude_region_longitude"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ["-priority", "-published_at"]},
        ),
        migrations.AddField(
            model_name="news",
            name="category",
            field=models.CharField(
                choices=[
                    ("일반", "일반"),
                    ("교통", "교통"),
                    ("교육", "교육"),
                    ("의료", "의료"),
                    ("주거", "주거"),
                    ("정책", "정책"),
                ],
                default="일반",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="is_realtime",
            field=models.BooleanField(
                default=False, help_text="실시간 업데이트된 뉴스"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="priority",
            field=models.IntegerField(
                default=0, help_text="우선순위 (높을수록 먼저 표시)"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="source_url",
            field=models.URLField(blank=True, help_text="뉴스 원본 URL"),
        ),
    ]
